"""
import section (get color)
"""

quiz_info = [
    {"question": "Q1. What is the Capital of Ireland:",
     "answers": {"A": "Galway",
                 "B": "Dublin",
                 "C": "Cork",
		         "D": "Galway"},
     "correct": "B"},
    {"question": "Q2. Who Created the Xbox:",
     "answers": {"A": "Sony",
                 "B": "Apple",
                 "C": "Nintendo",
		         "D": "Microsoft"},
     "correct": "D"},
    {"question": "Q3. Where is the Car manufacturers Audi From:",
     "answers": {"A": "Germany",
                 "B": "China",
                 "C": "USA",
		         "D": "Microsoft"},
     "correct": "A"},

    {"question": "Q4. Which of these is a Song from Red Hot Chilli Peppers:",
     "answers": {"A": "UpTown Girl",
                 "B": "Californation",
                 "C": "Adore You ",
                 "D": "Londons Burning"},
     "correct": "B"},
    {"question": "Q5. Which of these EU countries does not use the euro as its currency?",
     "answers": {"A": "Poland",
                 "B": "Denmark",
                 "C": "Sweeden",
		         "D": "All of the Above"},
     "correct": "D"},
    {"question": "Q6. What color dresses do Chinese women traditionally wear on their wedding day? ",
     "answers": {"A": "Blue",
                 "B": "Gold",
                 "C": "White",
		         "D": "Red"},
     "correct": "D"},
    {"question": "Q7. How many molecules of oxygen does ozone have?",
     "answers": {"A": "One",
                 "B": "Two",
                 "C": "Three",
		         "D": "Four"},
     "correct": "C"},
    {"question": "Q8. Where did the croissant originate?",
     "answers": {"A": "France",
                 "B": "Austria",
                 "C": "Turkey",
		         "D": "Tokyo"},
     "correct": "B"},
    {"question": "Q9. Pupusas are from what country",
     "answers": {"A": "Mexico",
                 "B": "El Salvador",
                 "C": "Brazil",
		         "D": "Poland"},
     "correct": "B"},
    {"question": "Final Question.  Which of these US presidents appeared on the television series 'Laugh-In'  ",
     "answers": {"A": "Lyndon Johnson",
                 "B": "Richard Nixon",
		         "C": "Jimmy Carter",
                 "D": "Gerald Ford"},
     "correct": "B"},
]

print(quiz_info)